services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: rpd_image:latest
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run uiServer
    networks:
      - app_network
    container_name: rpd_frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: rpd_image:latest
    working_dir: /app
    ports:
      - "8080:8080"
    command: npm run apiServer
    networks:
      - app_network
    container_name: rpd_backend

  mongodb:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    # image: mongodb_image:latest
    ports:
      - "27017:27017"
    networks:
      - app_network
    container_name: rpd_mongodb

networks:
  app_network:
    driver: bridge
